"""add transitional table tag-article

Revision ID: b33949c6c7ef
Revises: 64a35a022893
Create Date: 2021-09-13 14:09:59.550121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33949c6c7ef'
down_revision = '64a35a022893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_articles_tags_association_table',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['blog_articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_articles_tags_association_table')
    # ### end Alembic commands ###
