"""added bio tag in author

Revision ID: f1498c4c6c6a
Revises: b0179d0a5357
Create Date: 2021-09-13 12:12:13.425605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1498c4c6c6a'
down_revision = 'b0179d0a5357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_authors', sa.Column('bio', sa.Text(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_authors', 'bio')
    # ### end Alembic commands ###
