# Generated by Django 3.2 on 2021-09-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='length',
        ),
    ]
