# Generated by Django 3.2 on 2021-09-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animalprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animals.animal'),
        ),
    ]
